Build both supported architectures at once with a combined manifest

diff --git a/deploy/cephcsi/image/Dockerfile b/deploy/cephcsi/image/Dockerfile
--- a/deploy/cephcsi/image/Dockerfile
+++ b/deploy/cephcsi/image/Dockerfile
@@ -1,9 +1,8 @@
 ARG SRC_DIR="/go/src/github.com/ceph/ceph-csi/"
-ARG GO_ARCH
 ARG BASE_IMAGE
 ARG FINAL_BASE_IMAGE="quay.io/centos/centos:stream9-minimal"
 
-FROM ${BASE_IMAGE} as updated_base
+FROM --platform=${TARGETPLATFORM} ${BASE_IMAGE} as updated_base
 
 # TODO: remove the following cmd, when issues
 # https://github.com/ceph/ceph-container/issues/2034
@@ -20,13 +19,12 @@ RUN dnf -y update --nobest \
        && dnf clean all \
        && rm -rf /var/cache/yum
 
-FROM updated_base as builder
+FROM --platform=${TARGETPLATFORM} updated_base as builder
 
 LABEL stage="build"
 
 ARG CSI_IMAGE_NAME=quay.io/cephcsi/cephcsi
 ARG CSI_IMAGE_VERSION=canary
-ARG GO_ARCH
 ARG SRC_DIR
 ARG GIT_COMMIT
 ARG GO_BUILD_VERBOSE
@@ -35,7 +33,8 @@ ARG GOROOT=/usr/local/go
 COPY build.env /
 
 RUN source /build.env && \
-    ( test -n "${GO_ARCH}" && exit 0; echo -e "\n\nMissing GO_ARCH argument for building image, install Golang or run: make image-cephcsi GOARCH=amd64\n\n"; exit 1 ) && \
+    ( test -n "${TARGETPLATFORM}" && exit 0; echo -e "\n\nMissing TARGETPLATFORM argument for building image, run: make image-cephcsi PLATFORM=linux/amd64,linux/arm64\n\n"; exit 1 ) && \
+    export GO_ARCH="${TARGETPLATFORM#linux/}" && \
     mkdir -p ${GOROOT} && \
     curl -L https://go.dev/dl/go${GOLANG_VERSION}.linux-${GO_ARCH}.tar.gz | tar xzf - -C ${GOROOT} --strip-components=1
 
@@ -72,14 +71,14 @@ COPY . ${SRC_DIR}
 RUN make cephcsi GO_BUILD_VERBOSE="${GO_BUILD_VERBOSE}"
 
 #-- Final container
-FROM ${FINAL_BASE_IMAGE}
+FROM --platform=${TARGETPLATFORM} ${FINAL_BASE_IMAGE}
 
 ARG SRC_DIR
 ARG CEPH_VERSION
 
-LABEL maintainers="Ceph-CSI Authors" \
+LABEL maintainers="Northflank + Ceph-CSI Authors" \
     version=${CSI_IMAGE_VERSION} \
-    architecture=${GO_ARCH} \
+    architecture=${TARGETPLATFORM#linux/} \
     description="Ceph-CSI Plugin"
 
 COPY --from=builder ${SRC_DIR}/_output/cephcsi /usr/local/bin/cephcsi
